version: '3.8'
services:
  gateway:
    build: gateway
    image: java-shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: java-shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2://db:5432/shareit

  db:
    image: postgres:13.7-alpine
    container_name: postgresql
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root