DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS item_requests CASCADE;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                               NOT NULL,
    email VARCHAR(512)                              NOT NULL,
    CONSTRAINT pk_user                 PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL                   UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests (
    item_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY                                  NOT NULL,
    description VARCHAR(255)                                                                 NOT NULL,
    user_id BIGINT                                                                           NOT NULL,
    time_of_creation TIMESTAMP                                                               NOT NULL,
    response_items BIGINT,
    CONSTRAINT pk_item_request                                          PRIMARY KEY (item_request_id),
    CONSTRAINT fk_item_request_user_id FOREIGN KEY (user_id)                 REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY                                    NOT NULL,
    name VARCHAR(255)                                                                  NOT NULL,
    user_id BIGINT                                                                     NOT NULL,
    description VARCHAR(1024)                                                          NOT NULL,
    available BOOLEAN                                                             DEFAULT FALSE,
    request_id BIGINT,
    CONSTRAINT pk_item                                                    PRIMARY KEY (item_id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id)                        REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY                     NOT NULL,
    user_id BIGINT                                                         NOT NULL,
    item_id BIGINT                                                         NOT NULL,
    rating INTEGER                                                         ,
    text VARCHAR(1024)                                                     NOT NULL,
    time_of_creation TIMESTAMP                                                     ,
    CONSTRAINT pk_comment                                  PRIMARY KEY (comment_id),
    CONSTRAINT fk_comment_user_id FOREIGN KEY (user_id)   REFERENCES users(user_id),
    CONSTRAINT fk_comment_item_id FOREIGN KEY (item_id)   REFERENCES items(item_id)
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY                      NOT NULL,
    user_id BIGINT                                                          NOT NULL,
    item_id BIGINT                                                          NOT NULL,
    start_time TIMESTAMP                                                    NOT NULL,
    end_time TIMESTAMP                                                      NOT NULL,
    status VARCHAR(24),
    CONSTRAINT pk_booking PRIMARY KEY (booking_id),
    CONSTRAINT fk_bookings_user_id FOREIGN KEY (user_id)   REFERENCES users(user_id),
    CONSTRAINT fk_bookings_item_id FOREIGN KEY (item_id)    REFERENCES items(item_id)
);